name: CI Pipeline

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Validation du build Docker Compose
        run: |
          # temp .env file for CI pipeline
          echo "DB_HOST=db" > .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USER=db_user" >> .env
          echo "DB_PASSWORD=mypassword" >> .env
          echo "DB_NAME=the_name" >> .env
          echo "SECRET_KEY=ultrasecurePassword" >> .env

          docker compose build
      

      - name: Containers launch test
        run: |
          docker compose up -d
          sleep 10
          docker compose ps
      - name: Containers shutdown
        run: docker compose down -v